### ISSUE TITLE
Fix for "Invalid DateTime length"

### ISSUE THREAD

**Issue by DasFaultier** [SLUB-digitalpreservation/fixit_tiff#1]
string: "Tue Dec 19 09:18:54 2006%0A" should be fixed to "2006:12:19 09:18:54"

**Comment by ghost** [comment]
Hmm, the string above looks like the variant from strftime function. It could be hard to fix that, because the string above exceeds the 20bytes limit.

**Comment by ghost** [comment]
Ok, there is actually added a new rule to fix that kind of datetime strings in commit fc479df66b974f71c0baf08d2d48e2eb175f9b74
